### PR TITLE
MLFQ implementation 1

### PR DESCRIPTION
**Pull request by adiwajshing**

### CODE REVIEW

**Comment by Swastyy** [comment]
We don't have any mentor/maintainer here to see the PR's?

**Comment by nubok** [comment]
What reason do you have that you want this fork to be merged with the main xv6 repository?

Otherwise: this version of xv6 is barely maintained anymore. The developers now centrally invest their efforts on the RISC-V version of xv6:

https://github.com/mit-pdos/xv6-riscv
https://github.com/mit-pdos/xv6-riscv-book

**Comment by Swastyy** [comment]
I think if Xv6 operating system has its priority scheduling inbuilt within it will become more compatible for several processes running together, also including the interrepts.

**Comment by adiwajshing** [comment]
My bad, this PR was accidentally sent here. I'll close.

**Pull request closed without merging**
