### PR TITLE
Use full area (80x25) in monitor

### PR DESCRIPTION
**Pull request by tyfkda**
I don't know why,
but the last line in the monitor is not used.

If there is no reason,
I prefer to use full area.

### CODE REVIEW

**Comment by nubok** [comment]
I am just wondering whether the block

  if(pos < 0 || pos > 25*80)
    panic("pos under/overflow");

(after your patch) should be replaced by

  if(pos < 0 || pos >= 25*80)
    panic("pos under/overflow");

or not.

**Comment by anishathalye** [comment]
Isn’t 80x24 standard for terminal emulators? (From VT52/VT100)

**Comment by tyfkda** [comment]
@nubok I didn't change the code block,
but I think you are right.

**Comment by tyfkda** [comment]
@anishathalye Thank you for your information.
I still prefer to use 80x25 on current platform.

**Comment by kaashoek** [comment]
thanks, but we prefer the standard 80x24 for xv6.

**Pull request closed without merging**
