### PR TITLE
Update bootasm.S

### PR DESCRIPTION
**Pull request by Schummacher**

### CODE REVIEW

**Comment by alexkonradi** [comment]
While I can't speak for the maintainers, I'm not sure what this pull request is for. Unless I'm mistaken, the changes are either trivial or incorrect.

**Comment by ycoroneos** [comment]
Hi Schummacher can you explain your changes, especially the new push and pop on lines 28 and 34? I don't think replacing inb with pop is correct..

**Comment by nubok** [comment]
Since I was the person who introduced the "xorw    %ax,%ax" line for zeroing ax, which you replaced by "movw    $0, %ax": The canonical way (recommended by Intel) to zero a register in x86 is to use the xor instruction. Alternatively also "sub" works. You only use "movw $0, %reg" if the flags that are set  by xor or sub are of concern for your code (as you surely know mov does not change any flags). I could tell you more details, but if you are interested in a brief overview, read https://randomascii.wordpress.com/2012/12/29/the-surprising-subtleties-of-zeroing-a-register/

**Comment by Schummacher** [comment]
I am so sorry for this pull request, for my mistake pull request. I did want to pull it to this.

**Pull request closed without merging**
