### PR TITLE
Avoid GCC-specific features

### PR DESCRIPTION
**Pull request by jeehoonkang**
`usertests` said `ALL TESTS PASSED`.

- Remove the assembly label hack to refer %gs:0 and %gs:4
  http://stackoverflow.com/questions/39578898/what-does-the-declaration-extern-struct-cpu-cpu-asmgs0-mean/39581910#39581910

- Use the standard way to pass variable-length arguments (stdarg.h)

- Use C11 atomics (rather than x86.h's xchg)

- Improve Makefile by replacing `gcc` with `$(CC)`

### CODE REVIEW

**Comment by jeehoonkang** [comment]
FYI: I did it in order to port xv6 to Rust.  As a stepping stone I would like to port xv6 to Clang.  These changes are made in course of debugging xv6 on Clang.

https://github.com/jeehoonkang/xv6-public/tree/rust

**Comment by phf** [comment]
I may well be wrong about this, but I believe the xv6 source tries to stay away from "official" headers like stdarg.h and so on for a reason. Of course it may still be something you want to do for your project, but I'd be surprised if this gets merged.

**Comment by jeehoonkang** [comment]
@phf Thank you for the reply!  May I further ask what is the "reason" xv6 avoids relying on the C Standard?  I know that OS is beyond the scope of the Standard (e.g. context switching and low-level manipulation of physical/virtual memory), but IMHO for portability it is better to use the Standard C wherever possible, as evidenced by my experience on porting xv6 to Clang.  Note that there is a similar discussion for Linux (https://lkml.org/lkml/2014/2/14/503), and Linus himself doesn't like the idea of "the C Standard", while some other developers (including myself) feel otherwise.

**Comment by nubok** [comment]
@jeehoonkang

> May I further ask what is the "reason" xv6 avoids relying on the C Standard?

From looking at the source code I would assume that the xv6 authors are not opposed to rely on features of the C standard - quite the opposite. What they *do* want to avoid is to rely on features that need support from header files that are not part of the xv6 distribution. So for example the patch for console.c

> https://github.com/mit-pdos/xv6-public/pull/25/files#diff-e4f2f595efc7587439386c01ec8062e0

will surely be refused since it relies on the header file stdarg.h, which is not part of xv6. On the other hand: If you are willing to write your own version of stdarg.h that will be part of xv6 (and is sufficiently small and easy to understand so that "relying on the C standard" does not make the code more complicated), I can imagine quite well that the xv6 authors could be very interested to merge the changes into the next official xv6 version.

**Comment by kaashoek** [comment]
Thanks for encouraging us to remove the hack with %gs:0 and %gs:4, which had been on our todo list for a while.   We chose to remove the use of gs for curproc() completely so that xv6 uses only 1 piece of per-core state (lapiccpunum()).

**Pull request closed without merging**
